import { build } from 'esbuild';
import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';

const args = process.argv.slice(2);
if (args.length > 1 || (args.length === 1 && args[0] !== '--check')) {
  throw new Error('Usage: node plugins/hermes-realms/desktop/build.mjs [--check]');
}
const directory = fileURLToPath(new URL('.', import.meta.url));
const output = new URL('plugin.js', import.meta.url);
const result = await build({
  absWorkingDir: directory,
  entryPoints: ['plugin-source.js'],
  outfile: 'plugin.js',
  bundle: true,
  format: 'esm',
  platform: 'browser',
  target: 'es2022',
  external: ['@hermes/plugin-sdk', 'react', 'react/jsx-runtime'],
  sourcemap: false,
  legalComments: 'inline',
  charset: 'utf8',
  banner: { js: '// Generated by desktop/build.mjs from plugin-source.js. Do not edit.' },
  write: false,
});
const bytes = result.outputFiles[0].contents;
if (args[0] === '--check') {
  const current = await readFile(output);
  if (!current.equals(Buffer.from(bytes))) {
    throw new Error('Stale desktop/plugin.js; run node plugins/hermes-realms/desktop/build.mjs');
  }
  console.log('desktop/plugin.js is up to date');
} else {
  await writeFile(output, bytes);
  console.log('Built desktop/plugin.js');
}
