// Generated by desktop/build.mjs from plugin-source.js. Do not edit.

// plugin-source.js
import { host, SESSION_AREAS, useQuery as useQuery3, Button as Button4, Badge, ConfirmDialog as ConfirmDialog4, DropdownMenu, DropdownMenuTrigger, DropdownMenuContent, DropdownMenuItem } from "@hermes/plugin-sdk";
import { useState as useState4, useRef as useRef4, useEffect as useEffect4 } from "react";
import { jsx as jsx4, jsxs as jsxs4 } from "react/jsx-runtime";

// setup-controls.js
import { Button, ConfirmDialog, SegmentedControl, usePluginI18n, useQuery, useQueryClient } from "@hermes/plugin-sdk";
import { useEffect, useRef, useState } from "react";
import { jsx, jsxs } from "react/jsx-runtime";
var setupLocales = {
  en: {
    updateUncertain: "Update outcome unknown. Refresh status before checking again.",
    updateCancel: "Cancel update",
    updateReadError: "Connection interrupted. Refresh update status.",
    updateCheck: "Check for updates",
    updateTitle: "Review base update",
    updateConfirm: "Update",
    updateLater: "Later",
    updateScope: "Base image for this profile; approved packages affect the gateway host. Retained workspaces are kept.",
    updateCurrent: "Base image is up to date.",
    updateUnknown: "Latest base version unavailable.",
    updateReviewError: "Update review unavailable or changed. Check again.",
    storageTitle: "Storage and base image",
    storageLabel: "Omarchy storage",
    storageBase: "Omarchy base",
    storageLoading: "Reading storage…",
    storageError: "Storage unavailable. Refresh to try again.",
    storageUnknown: "Unknown",
    storageNotPrepared: "Not prepared",
    storagePrepared: "Prepared",
    storageDownloads: "Downloaded files",
    storageBaseFiles: "Base image files",
    storageWorkspaces: "VM workspace files",
    storageRetained: "Stop retains workspace data. Export needed work before using Delete in the conversation’s management menu.",
    permissionHeld: "Execution paused for permission review",
    legacyHost: "Legacy host access retained · private testing disabled",
    permissionReview: "Use optional targets…",
    permissionTitle: "Review conversation permissions",
    permissionAccept: "Accept permission change",
    permissionError: "Permission review unavailable or changed. Close and review again. No guest was changed.",
    manage: "Manage private testing",
    popout: "Pop out",
    stopTesting: "Stop private testing",
    disableTesting: "Disable use for this session",
    actionError: "Action failed. Refresh status before trying again.",
    deleteAction: "Delete workspace…",
    retryDelete: "Retry deletion…",
    deleteTitle: "Delete retained workspace?",
    deleteConfirm: "Delete workspace",
    deleteWarning: "This permanently removes the selected private workspace. Export any work you need before deleting. The original host project and shared base image are kept.",
    deleteError: "Deletion unavailable or workspace changed. Close and review again. Running work must be stopped first.",
    deleteRefreshError: "Workspace deleted. Refresh status to update this view.",
    testingEnabled: "Private testing enabled",
    testingDisabled: "Private testing disabled",
    testingUnselected: "Private testing not selected",
    deletingState: "deleting",
    stoppedState: "stopped",
    recoveryState: "needs recovery",
    cleanupState: "cleanup incomplete",
    realm: "Realm",
    vm: "Omarchy VM",
    repair: "Repair",
    install: "Set up",
    start: "Use this desktop",
    repairAction: "Repair…",
    installAction: "Set up…",
    vmAction: "Set up Omarchy VM…",
    switchAction: "Use this desktop…",
    reviewTitle: "Review desktop setup",
    details: "Details",
    ready: "Ready",
    needsRepair: "Needs setup or repair",
    needsVm: "A disposable Omarchy desktop with its own kernel and disk.",
    checking: "Checking setup…",
    started: "Setup started",
    running: "Preparing desktop…",
    failed: "Setup failed",
    cancelSetup: "Cancel setup",
    cancelling: "Cancelling…",
    cancelled: "Setup cancelled",
    cancelPending: "Requesting cancellation…",
    retry: "Retry…",
    connectionLost: "Connection interrupted. Setup may still be running.",
    reviewChanged: "Setup requirements changed. Review the updated details before confirming.",
    error: "Unable to prepare this desktop. Try again.",
    scoped: "Desktop choice: this chat. Driver and base image: this profile. Approved system packages affect the gateway host. Nothing is installed before you confirm."
  },
  ru: {
    updateUncertain: "Результат обновления неизвестен. Обновите статус перед новой проверкой.",
    updateCancel: "Отменить обновление",
    updateReadError: "Соединение прервано. Обновите статус обновления.",
    updateCheck: "Проверить обновления",
    updateTitle: "Проверка обновления базового образа",
    updateConfirm: "Обновить",
    updateLater: "Позже",
    updateScope: "Базовый образ для этого профиля; одобренные пакеты устанавливаются на сервер шлюза. Рабочие области сохраняются.",
    updateCurrent: "Базовый образ актуален.",
    updateUnknown: "Последняя версия базового образа недоступна.",
    updateReviewError: "Проверка обновления недоступна или изменилась. Проверьте снова.",
    storageTitle: "Хранилище и базовый образ",
    storageLabel: "Хранилище Omarchy",
    storageBase: "Базовый образ Omarchy",
    storageLoading: "Чтение хранилища…",
    storageError: "Хранилище недоступно. Обновите для повторной попытки.",
    storageUnknown: "Неизвестно",
    storageNotPrepared: "Не подготовлен",
    storagePrepared: "Подготовлен",
    storageDownloads: "Загруженные файлы",
    storageBaseFiles: "Файлы базового образа",
    storageWorkspaces: "Файлы рабочих областей ВМ",
    storageRetained: "Остановка сохраняет рабочие данные. Экспортируйте нужные файлы перед удалением через меню управления беседой.",
    permissionHeld: "Выполнение приостановлено для проверки разрешений",
    legacyHost: "Прежний доступ к хосту сохранён · приватное тестирование отключено",
    permissionReview: "Использовать отдельные цели…",
    permissionTitle: "Проверка разрешений беседы",
    permissionAccept: "Принять изменение разрешений",
    permissionError: "Проверка разрешений недоступна или изменилась. Закройте и проверьте снова. Гостевая система не изменена.",
    manage: "Управление изолированным тестированием",
    popout: "Отдельное окно",
    stopTesting: "Остановить изолированное тестирование",
    disableTesting: "Отключить для этого сеанса",
    actionError: "Не удалось выполнить действие. Обновите статус перед повторной попыткой.",
    deleteAction: "Удалить рабочую область…",
    retryDelete: "Повторить удаление…",
    deleteTitle: "Удалить сохранённую рабочую область?",
    deleteConfirm: "Удалить рабочую область",
    deleteWarning: "Выбранная приватная рабочая область будет удалена навсегда. Сначала экспортируйте нужные файлы. Исходный проект на хосте и общий базовый образ сохранятся.",
    deleteError: "Удаление недоступно или рабочая область изменилась. Закройте и проверьте снова. Сначала остановите запущенную работу.",
    deleteRefreshError: "Рабочая область удалена. Обновите статус.",
    testingEnabled: "Изолированное тестирование включено",
    testingDisabled: "Изолированное тестирование отключено",
    testingUnselected: "Изолированное тестирование не выбрано",
    deletingState: "удаляется",
    stoppedState: "остановлено",
    recoveryState: "требуется восстановление",
    cleanupState: "очистка не завершена",
    realm: "Realm",
    vm: "Omarchy VM",
    repair: "Исправить",
    install: "Настроить",
    start: "Использовать этот рабочий стол",
    repairAction: "Исправить…",
    installAction: "Настроить…",
    vmAction: "Настроить Omarchy VM…",
    switchAction: "Использовать этот рабочий стол…",
    reviewTitle: "Проверка настройки рабочего стола",
    details: "Подробности",
    ready: "Готово",
    needsRepair: "Требуется настройка или исправление",
    needsVm: "Одноразовый рабочий стол Omarchy с отдельным ядром и диском.",
    checking: "Проверка настройки…",
    started: "Настройка запущена",
    running: "Подготовка рабочего стола…",
    failed: "Не удалось настроить",
    cancelSetup: "Отменить настройку",
    cancelling: "Отмена…",
    cancelled: "Настройка отменена",
    cancelPending: "Запрос отмены…",
    retry: "Повторить…",
    connectionLost: "Соединение прервано. Настройка может продолжаться.",
    reviewChanged: "Требования изменились. Проверьте обновлённые сведения перед подтверждением.",
    error: "Не удалось подготовить рабочий стол. Повторите попытку.",
    scoped: "Рабочий стол — для этого чата; драйвер и базовый образ — для этого профиля. Одобренные системные пакеты устанавливаются на сервер шлюза. Установка начнётся после подтверждения."
  },
  zh: {
    updateUncertain: "更新结果未知。请刷新状态后再检查。",
    updateCancel: "取消更新",
    updateReadError: "连接中断。请刷新更新状态。",
    updateCheck: "检查更新",
    updateTitle: "审核基础镜像更新",
    updateConfirm: "更新",
    updateLater: "稍后",
    updateScope: "此配置的基础镜像；批准的软件包会安装到网关主机。保留的工作区不会删除。",
    updateCurrent: "基础镜像已是最新版本。",
    updateUnknown: "无法获取最新基础镜像版本。",
    updateReviewError: "更新审核不可用或已更改。请重新检查。",
    storageTitle: "存储和基础镜像",
    storageLabel: "Omarchy 存储",
    storageBase: "Omarchy 基础镜像",
    storageLoading: "正在读取存储…",
    storageError: "存储不可用。请刷新重试。",
    storageUnknown: "未知",
    storageNotPrepared: "尚未准备",
    storagePrepared: "已准备",
    storageDownloads: "已下载的文件",
    storageBaseFiles: "基础镜像文件",
    storageWorkspaces: "虚拟机工作区文件",
    storageRetained: "停止会保留工作区数据。在会话管理菜单中使用删除前，请先导出需要保留的文件。",
    permissionHeld: "执行已暂停，等待权限审核",
    legacyHost: "保留原有主机访问权限 · 私有测试已禁用",
    permissionReview: "使用可选目标…",
    permissionTitle: "审核会话权限",
    permissionAccept: "接受权限变更",
    permissionError: "权限审核不可用或已更改。请关闭并重新审核。未更改任何访客环境。",
    manage: "管理私有桌面测试",
    popout: "独立窗口",
    stopTesting: "停止私有桌面测试",
    disableTesting: "在此会话中禁用",
    actionError: "操作失败。请先刷新状态再重试。",
    deleteAction: "删除工作区…",
    retryDelete: "重试删除…",
    deleteTitle: "删除保留的工作区？",
    deleteConfirm: "删除工作区",
    deleteWarning: "这会永久删除选定的私有工作区。删除前请导出需要保留的文件。主机上的原始项目和共享基础镜像将保留。",
    deleteError: "无法删除或工作区已更改。请关闭并重新审核。必须先停止运行中的任务。",
    deleteRefreshError: "工作区已删除。请刷新状态以更新此视图。",
    testingEnabled: "已启用私有桌面测试",
    testingDisabled: "已禁用私有桌面测试",
    testingUnselected: "尚未选择私有桌面测试",
    deletingState: "正在删除",
    stoppedState: "已停止",
    recoveryState: "需要恢复",
    cleanupState: "清理未完成",
    realm: "Realm",
    vm: "Omarchy VM",
    repair: "修复",
    install: "设置",
    start: "使用此桌面",
    repairAction: "修复…",
    installAction: "设置…",
    vmAction: "设置 Omarchy VM…",
    switchAction: "使用此桌面…",
    reviewTitle: "确认桌面设置",
    details: "详细信息",
    ready: "就绪",
    needsRepair: "需要设置或修复",
    needsVm: "拥有独立内核和磁盘的一次性 Omarchy 桌面。",
    checking: "正在检查…",
    started: "设置已开始",
    running: "正在准备桌面…",
    failed: "设置失败",
    cancelSetup: "取消设置",
    cancelling: "正在取消…",
    cancelled: "设置已取消",
    cancelPending: "正在请求取消…",
    retry: "重试…",
    connectionLost: "连接中断。设置可能仍在进行。",
    reviewChanged: "设置要求已更改。请查看更新后的详情再确认。",
    error: "无法准备此桌面。请重试。",
    scoped: "桌面选择仅适用于此聊天，驱动和基础镜像仅用于此配置。批准的系统软件包会安装到网关主机。在您确认之前不会安装任何内容。"
  }
};
var ownerBody = (session) => Object.fromEntries([
  ["runtime_session_id", session.runtimeSessionId],
  ["stored_session_id", session.storedSessionId]
].filter(([, value]) => typeof value === "string" && value.length));
var running = (job) => ["running", "cancelling"].includes(job?.state);
var finished = (job) => ["succeeded", "failed", "cancelled"].includes(job?.state);
var validReview = (value) => value && ["realm", "omarchy-vm"].includes(value.kind) && ["repair", "install", "start"].includes(value.action) && typeof value.summary === "string" && Array.isArray(value.details) && value.details.every((detail) => typeof detail === "string") && typeof value.consent === "string" && value.consent.length > 0;
function useRealmText() {
  const translate = usePluginI18n("hermes-realms");
  return (key) => {
    const value = translate(key);
    return value === key ? setupLocales.en[key] : value;
  };
}
function RealmSetupControls({ ctx, session, data, refresh }) {
  const t = useRealmText();
  const queryClient = useQueryClient();
  const [cancelPending, setCancelPending] = useState(false);
  const currentKind = data.kind || "realm";
  const [choice, setChoice] = useState(null);
  const kind = choice || data.requested_kind || currentKind;
  const [review, setReview] = useState(null);
  const [preparing, setPreparing] = useState(false);
  const [error, setError] = useState(null);
  const [started, setStarted] = useState(null);
  const mounted = useRef(true);
  const pending = useRef(false);
  useEffect(() => {
    mounted.current = true;
    return () => {
      mounted.current = false;
    };
  }, []);
  useEffect(() => {
    if (started && data.setup_job?.id === started.id && (!finished(started) || finished(data.setup_job))) setStarted(null);
  }, [started, data.setup_job]);
  const jobSeed = started && !(data.setup_job?.id === started.id && finished(data.setup_job)) ? started : data.setup_job;
  const jobKey = ["hermes-realms-setup", session.connectionId, session.profile, session.storedSessionId, session.runtimeSessionId, jobSeed?.id];
  const jobResult = useQuery({
    queryKey: jobKey,
    enabled: Boolean(jobSeed?.id) && running(jobSeed),
    queryFn: () => ctx.rest(`/realms/setup/jobs/${encodeURIComponent(jobSeed.id)}?${new URLSearchParams(ownerBody(session))}`, { scope: session }),
    refetchInterval: (query) => running(query.state.data || jobSeed) ? 1e3 : false,
    retry: 1,
    gcTime: 6e4
  });
  const job = finished(jobSeed) ? jobSeed : jobResult.data || jobSeed;
  const jobError = jobResult.isError && !finished(job);
  const busy = preparing || review !== null || running(job);
  const refreshed = useRef(null);
  useEffect(() => {
    if (job?.state === "succeeded" && refreshed.current !== job.id) {
      refreshed.current = job.id;
      void refresh();
    }
  }, [job?.id, job?.state, refresh]);
  const setup = kind === "omarchy-vm" ? data.vm_setup : data.setup;
  const ready = setup?.ready === true;
  const needsAction = !ready || kind !== currentKind || data.mode !== "realm";
  async function prepare() {
    if (pending.current || running(job)) return;
    pending.current = true;
    setPreparing(true);
    setError(null);
    const scope = Object.freeze({ ...session });
    try {
      const value = await ctx.rest("/realms/setup/prepare", { method: "POST", body: { ...ownerBody(scope), kind }, scope });
      if (!validReview(value) || value.kind !== kind) throw new Error(t("error"));
      if (mounted.current) setReview({ value, scope });
    } catch (failure) {
      if (mounted.current) setError(failure instanceof Error ? failure.message : t("error"));
    } finally {
      pending.current = false;
      if (mounted.current) setPreparing(false);
    }
  }
  async function cancelJob() {
    if (!mounted.current || pending.current || job?.state !== "running" || job.cancellable === false) return;
    pending.current = true;
    setCancelPending(true);
    const scope = Object.freeze({ ...session });
    const id = job.id;
    try {
      const receipt = await ctx.rest(`/realms/setup/jobs/${encodeURIComponent(id)}/cancel`, {
        method: "POST",
        body: ownerBody(scope),
        scope
      });
      if (receipt?.id !== id || !["running", "cancelling", "cancelled", "succeeded", "failed"].includes(receipt.state)) throw new Error(t("error"));
      await queryClient.cancelQueries({ queryKey: jobKey, exact: true });
      queryClient.setQueryData(jobKey, receipt);
      if (mounted.current) setError(null);
    } catch (failure) {
      if (mounted.current) setError(failure instanceof Error ? failure.message : t("error"));
    } finally {
      pending.current = false;
      if (mounted.current) setCancelPending(false);
    }
  }
  async function confirm() {
    if (!mounted.current || pending.current || !review) return;
    pending.current = true;
    const { value, scope } = review;
    try {
      const receipt = await ctx.rest("/realms/setup/start", {
        method: "POST",
        body: { ...ownerBody(scope), kind: value.kind, consent: value.consent },
        scope
      });
      if (!receipt?.id || !["running", "succeeded", "failed"].includes(receipt.state)) throw new Error(t("error"));
      if (receipt.state === "failed") throw new Error(receipt.message || t("failed"));
      if (mounted.current) {
        setStarted(receipt);
        setError(null);
        if (receipt.state === "succeeded") await refresh();
      }
    } catch (failure) {
      let changed = false;
      if (mounted.current) {
        try {
          const next = await ctx.rest("/realms/setup/prepare", { method: "POST", body: { ...ownerBody(scope), kind: value.kind }, scope });
          if (mounted.current && validReview(next) && next.kind === value.kind && JSON.stringify(next.consent) !== JSON.stringify(value.consent)) {
            setReview({ value: next, scope });
            changed = true;
          }
        } catch {
        }
      }
      if (changed) throw new Error(t("reviewChanged"));
      throw failure;
    } finally {
      pending.current = false;
    }
  }
  if (data.requested !== void 0 && !needsAction && !busy && !error && !["failed", "cancelled"].includes(job?.state) && !jobError) return null;
  const actionLabel = error || ["failed", "cancelled"].includes(job?.state) ? t("retry") : kind === "omarchy-vm" && !ready ? t("vmAction") : !ready ? t("repairAction") : t("switchAction");
  const status = preparing ? t("checking") : running(job) ? job.message || t("running") : job?.state === "cancelled" ? t("cancelled") : kind === currentKind && data.mode === "host" ? t("testingDisabled") : kind === currentKind && data.mode === "ask" ? t("testingUnselected") : ready && kind === currentKind && data.mode === "realm" ? t("ready") : kind === "omarchy-vm" ? t("needsVm") : t("needsRepair");
  return jsxs("div", { className: "flex flex-col gap-2 text-xs", "data-realms-setup": "", children: [
    jsxs("div", { className: "flex flex-wrap items-center gap-2", children: [
      data.requested === void 0 && jsx(SegmentedControl, {
        options: [{ id: "realm", label: t("realm") }, { id: "omarchy-vm", label: t("vm") }],
        value: kind,
        disabled: busy,
        onChange: (next) => {
          setChoice(next);
          setError(null);
        }
      }),
      jsx("span", { role: "status", className: "text-muted-foreground", children: status }),
      running(job) && jsx(Button, {
        size: "micro",
        variant: "ghost",
        disabled: cancelPending || job.state === "cancelling" || job.cancellable === false,
        onClick: () => void cancelJob(),
        children: cancelPending ? t("cancelPending") : job.state === "cancelling" ? t("cancelling") : t("cancelSetup")
      }),
      (needsAction || job?.state === "cancelled") && !running(job) && jsx(Button, {
        size: "micro",
        variant: "ghost",
        disabled: busy,
        onClick: () => void prepare(),
        children: actionLabel
      })
    ] }),
    (error || job?.state === "failed" || jobError) && jsx("div", { role: "alert", children: error || (jobError ? t("connectionLost") : job.message || t("failed")) }),
    review && jsx(ConfirmDialog, {
      open: true,
      title: t("reviewTitle"),
      confirmLabel: t(review.value.action),
      busyLabel: t("checking"),
      doneLabel: t("started"),
      onClose: () => setReview(null),
      onConfirm: confirm,
      description: jsxs("span", { className: "flex flex-col gap-3", children: [
        jsx("span", { children: review.value.summary }),
        jsx("span", { children: t("scoped") }),
        review.value.details.length > 0 && jsxs("details", { children: [
          jsx("summary", { children: t("details") }),
          ...review.value.details.map((detail, index) => jsx("span", { className: "block break-words", children: detail }, index))
        ] })
      ] })
    })
  ] });
}

// permission-controls.js
import { Button as Button2, ConfirmDialog as ConfirmDialog2 } from "@hermes/plugin-sdk";
import { useEffect as useEffect2, useRef as useRef2, useState as useState2 } from "react";
import { jsx as jsx2, jsxs as jsxs2 } from "react/jsx-runtime";
var ownerBody2 = (session) => Object.fromEntries([
  ["runtime_session_id", session.runtimeSessionId],
  ["stored_session_id", session.storedSessionId]
].filter(([, value]) => typeof value === "string" && value.length));
function RealmPermissionControls({ ctx, session, data, refresh }) {
  const t = useRealmText();
  const [review, setReview] = useState2(null);
  const [error, setError] = useState2(null);
  const [busy, setBusy] = useState2(false);
  const mounted = useRef2(true);
  const pending = useRef2(false);
  useEffect2(() => {
    mounted.current = true;
    return () => {
      mounted.current = false;
    };
  }, []);
  async function prepare() {
    if (pending.current) return;
    pending.current = true;
    setBusy(true);
    setError(null);
    const scope = Object.freeze({ ...session });
    const rest = ctx.rest.bind(ctx);
    try {
      const value = await rest("/realms/permissions/prepare", { method: "POST", body: ownerBody2(scope), scope });
      if (typeof value?.digest !== "string" || typeof value.text !== "string" || !Array.isArray(value.resources)) throw new Error();
      if (mounted.current) setReview({ value, scope, rest });
    } catch {
      if (mounted.current) setError(t("permissionError"));
    } finally {
      pending.current = false;
      if (mounted.current) setBusy(false);
    }
  }
  async function accept() {
    if (!mounted.current || pending.current || !review) throw new Error(t("permissionError"));
    pending.current = true;
    try {
      const { value, scope, rest } = review;
      const result = await rest("/realms/permissions/accept", {
        method: "POST",
        body: { ...ownerBody2(scope), digest: value.digest },
        scope
      });
      if (result?.state !== "optional") throw new Error();
      if (mounted.current) await refresh();
    } catch {
      throw new Error(t("permissionError"));
    } finally {
      pending.current = false;
    }
  }
  return jsxs2("div", { className: "flex flex-col gap-2 text-xs", "data-realms-permission": "", children: [
    jsxs2("div", { className: "flex flex-wrap items-center gap-2", children: [
      jsx2("span", { role: "status", children: t(data.permission.state === "legacy-host" ? "legacyHost" : "permissionHeld") }),
      jsx2(Button2, { size: "micro", variant: "ghost", disabled: busy || !!review, onClick: () => void prepare(), children: t("permissionReview") })
    ] }),
    error && jsx2("span", { role: "alert", children: error }),
    review && jsx2(ConfirmDialog2, {
      open: true,
      title: t("permissionTitle"),
      confirmLabel: t("permissionAccept"),
      onClose: () => setReview(null),
      onConfirm: accept,
      description: jsxs2("span", { className: "flex flex-col gap-3", children: [
        jsx2("span", { children: `${review.scope.connectionId} · ${review.scope.profile} · ${review.scope.storedSessionId || review.scope.runtimeSessionId}` }),
        jsx2("span", { children: review.value.text }),
        ...review.value.resources.map((row) => jsx2("span", { children: `${row.id}: ${row.warning}` }, row.id))
      ] })
    })
  ] });
}

// storage-controls.js
import { Button as Button3, ConfirmDialog as ConfirmDialog3, useQuery as useQuery2, useQueryClient as useQueryClient2 } from "@hermes/plugin-sdk";
import { useEffect as useEffect3, useId, useRef as useRef3, useState as useState3 } from "react";
import { jsx as jsx3, jsxs as jsxs3 } from "react/jsx-runtime";
function storedSize(bytes, unknown) {
  if (!Number.isSafeInteger(bytes) || bytes < 0) return unknown;
  const units = ["B", "KiB", "MiB", "GiB", "TiB"];
  let unit = 0;
  while (bytes >= 1024 && unit < units.length - 1) {
    bytes /= 1024;
    unit += 1;
  }
  return `${Number.isInteger(bytes) ? bytes : bytes.toFixed(1)} ${units[unit]}`;
}
var validRelease = (value) => typeof value === "string" && /^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)$/.test(value);
var profileUpdate = (value) => value?.operation === "vm-base-update" && value.scope === "profile" && value.kind === "omarchy-vm";
var active = (job) => ["running", "cancelling"].includes(job?.state);
var terminal = (job) => ["succeeded", "failed", "cancelled"].includes(job?.state);
var validJob = (job) => profileUpdate(job) && typeof job.id === "string" && /^[a-f0-9]{32}$/.test(job.id) && (active(job) || terminal(job)) && typeof job.message === "string" && typeof job.cancellable === "boolean" && (job.error === void 0 || typeof job.error === "string") && (job.base_commit_started === void 0 || typeof job.base_commit_started === "boolean");
var strings = (value) => Array.isArray(value) && value.every((item) => typeof item === "string");
var validReview2 = (value, release, scope) => profileUpdate(value) && value.release === release && value.review_binding?.connectionId === scope.connectionId && value.review_binding?.profile === scope.profile && typeof value.consent === "string" && value.consent.trim().length > 0 && typeof value.summary === "string" && strings(value.details) && strings(value.blockers) && !value.blockers.length;
function RealmStorageSettings({ ctx, scope }) {
  if (!scope || !["connectionId", "profile"].every((key) => typeof scope[key] === "string" && scope[key].length)) return null;
  const binding = Object.freeze({ connectionId: scope.connectionId, profile: scope.profile });
  return jsx3(StorageSection, { ctx, scope: binding }, JSON.stringify(binding));
}
function StorageSection({ ctx, scope }) {
  const t = useRealmText();
  const mounted = useRef3(true);
  const pending = useRef3(false);
  const [request] = useState3(() => ctx.rest.bind(ctx));
  useEffect3(() => {
    mounted.current = true;
    return () => {
      mounted.current = false;
    };
  }, []);
  const [open, setOpen] = useState3(false);
  const queryClient = useQueryClient2();
  const [cancelPending, setCancelPending] = useState3(false);
  const [started, setStarted] = useState3(null);
  const [uncertain, setUncertain] = useState3(false);
  const id = useId();
  const [review, setReview] = useState3(null);
  const [detailsOpen, setDetailsOpen] = useState3(false);
  const detailsId = useId();
  const [checking, setChecking] = useState3(false);
  const [notice, setNotice] = useState3(null);
  async function checkUpdates() {
    if (!mounted.current || pending.current || review || uncertain || active(job)) return;
    pending.current = true;
    setChecking(true);
    setNotice(null);
    try {
      const latest = await request("/realms/vm/settings?check_updates=true", { scope });
      if (!mounted.current) return;
      if (latest.update?.available !== true) {
        setNotice(t(latest.update?.available === false ? "updateCurrent" : "updateUnknown"));
        return;
      }
      if (!validRelease(latest.update.latest)) throw new Error();
      const value = await request("/realms/vm/update/prepare", {
        method: "POST",
        body: { release: latest.update.latest, review_binding: scope },
        scope
      });
      if (!mounted.current) return;
      if (!validReview2(value, latest.update.latest, scope)) throw new Error();
      setDetailsOpen(false);
      setReview({ value });
    } catch {
      if (mounted.current) setNotice(t("updateReviewError"));
    } finally {
      pending.current = false;
      if (mounted.current) setChecking(false);
    }
  }
  const result = useQuery2({
    queryKey: ["hermes-realms-storage", scope.connectionId, scope.profile],
    queryFn: () => request("/realms/vm/settings", { scope }),
    enabled: open || active(started),
    staleTime: 5e3,
    retry: 1
  });
  const latestJob = validJob(result.data?.base_update_job) ? result.data.base_update_job : null;
  useEffect3(() => {
    if (started && latestJob?.id === started.id && (!terminal(started) || terminal(latestJob))) setStarted(null);
  }, [started, latestJob]);
  const seed = started && !(latestJob?.id === started.id && terminal(latestJob)) ? started : latestJob;
  const jobKey = ["hermes-realms-base-update", scope.connectionId, scope.profile, seed?.id];
  const jobResult = useQuery2({
    queryKey: jobKey,
    enabled: Boolean(seed) && active(seed),
    queryFn: async () => {
      const value = await request(`/realms/vm/update/jobs/${seed.id}`, { scope });
      if (!validJob(value) || value.id !== seed.id) throw new Error();
      return value;
    },
    refetchInterval: (query) => query.state.status !== "error" && active(query.state.data || seed) ? 1e3 : false,
    retry: false
  });
  const job = terminal(seed) ? seed : jobResult.data || seed;
  const refreshed = useRef3(null);
  useEffect3(() => {
    if (terminal(job) && active(seed) && refreshed.current !== job.id) {
      refreshed.current = job.id;
      void result.refetch();
    }
  }, [job, seed, result.refetch]);
  const readError = jobResult.isError && !terminal(seed) || result.isError && Boolean(job);
  async function refreshUpdate() {
    const reads = [result.refetch()];
    if (seed) reads.push(jobResult.refetch());
    const [latest] = await Promise.all(reads);
    if (mounted.current && !latest.isError) {
      setUncertain(false);
      setNotice(null);
    }
  }
  async function cancelJob() {
    if (!mounted.current || pending.current || job?.state !== "running" || !job.cancellable || job.base_commit_started) return;
    pending.current = true;
    setCancelPending(true);
    try {
      const value = await request(`/realms/vm/update/jobs/${job.id}/cancel`, { method: "POST", body: {}, scope });
      if (!validJob(value) || value.id !== job.id) throw new Error();
      if (!mounted.current) return;
      await queryClient.cancelQueries({ queryKey: jobKey, exact: true });
      queryClient.setQueryData(jobKey, value);
    } catch {
      if (mounted.current) {
        setNotice(t("updateReadError"));
        setUncertain(true);
      }
    } finally {
      pending.current = false;
      if (mounted.current) setCancelPending(false);
    }
  }
  const base = result.data?.base;
  const version = base?.present === false ? t("storageNotPrepared") : base?.present === true ? typeof base.version === "string" && base.version || t("storagePrepared") : t("storageUnknown");
  return jsxs3("div", { className: "flex flex-col items-start gap-2 text-xs", children: [
    jsx3(Button3, {
      size: "micro",
      variant: "ghost",
      "aria-expanded": open,
      "aria-controls": id,
      onClick: () => setOpen((value) => !value),
      children: t("storageTitle")
    }),
    open && jsxs3("div", { id, role: "region", "aria-label": t("storageLabel"), className: "flex flex-col gap-2", children: [
      jsx3("span", { className: "text-(--ui-text-tertiary)", children: `${scope.connectionId} · ${scope.profile}` }),
      jsx3(Button3, {
        size: "micro",
        variant: "ghost",
        disabled: checking || Boolean(review) || active(job) || uncertain,
        onClick: () => void checkUpdates(),
        children: t("updateCheck")
      }),
      (notice || job || uncertain) && jsxs3("div", { role: "status", className: "flex flex-wrap items-center gap-2", children: [
        jsx3("span", { children: job?.message || notice }),
        job && notice && !readError && jsx3("span", { children: notice }),
        readError && jsx3("span", { children: t("updateReadError") }),
        (readError || uncertain) && jsx3(Button3, {
          size: "micro",
          variant: "ghost",
          disabled: result.isFetching || jobResult.isFetching,
          onClick: () => void refreshUpdate(),
          children: t("retry")
        }),
        !uncertain && !readError && job?.state === "running" && job.cancellable && !job.base_commit_started && jsx3(Button3, {
          size: "micro",
          variant: "ghost",
          disabled: cancelPending,
          onClick: () => void cancelJob(),
          children: t("updateCancel")
        })
      ] }),
      result.isError && !job && !uncertain ? jsxs3("div", { role: "status", children: [
        t("storageError"),
        " ",
        jsx3(Button3, {
          size: "micro",
          variant: "ghost",
          disabled: result.isFetching,
          onClick: () => void result.refetch(),
          children: t("retry")
        })
      ] }) : result.isPending ? jsx3("span", { role: "status", children: t("storageLoading") }) : jsxs3("div", {
        className: "flex flex-col gap-2",
        children: [
          jsxs3("span", { children: [t("storageBase"), ": ", jsx3("span", { children: version })] }),
          jsx3("dl", {
            className: "grid grid-cols-[1fr_auto] gap-x-4 gap-y-1",
            children: [["iso_bytes", "storageDownloads"], ["base_bytes", "storageBaseFiles"], ["session_bytes", "storageWorkspaces"]].flatMap(([field, label]) => [
              jsx3("dt", { children: t(label) }, `${field}-label`),
              jsx3("dd", { children: storedSize(result.data?.storage?.[field], t("storageUnknown")) }, field)
            ])
          }),
          jsx3("span", { className: "text-(--ui-text-tertiary)", children: t("storageRetained") })
        ]
      })
    ] }),
    review && jsx3(ConfirmDialog3, {
      open: true,
      title: t("updateTitle"),
      confirmLabel: t("updateConfirm"),
      cancelLabel: t("updateLater"),
      onClose: () => setReview((current) => current === review ? null : current),
      onConfirm: async () => {
        if (!mounted.current || pending.current || review.used) return;
        review.used = true;
        pending.current = true;
        const { value } = review;
        try {
          const receipt = await request("/realms/vm/update/start", {
            method: "POST",
            body: { release: value.release, review_binding: scope, consent: value.consent },
            scope
          });
          if (!validJob(receipt)) throw new Error();
          if (!mounted.current) return;
          setStarted(receipt);
          setNotice(null);
          void result.refetch();
        } catch {
          if (!mounted.current) return;
          setReview((current) => current === review ? null : current);
          setUncertain(true);
          setNotice(t("updateUncertain"));
          void result.refetch();
        } finally {
          pending.current = false;
        }
      },
      description: jsxs3("span", { className: "flex flex-col gap-3", children: [
        jsx3("span", { children: review.value.summary }),
        jsx3("span", { children: `${t("updateScope")} ${scope.connectionId} · ${scope.profile}` }),
        jsxs3("span", { children: [
          jsx3(Button3, {
            type: "button",
            size: "inline",
            variant: "text",
            "aria-expanded": detailsOpen,
            "aria-controls": detailsId,
            onClick: () => setDetailsOpen((value) => !value),
            children: t("details")
          }),
          jsx3("span", { id: detailsId, hidden: !detailsOpen, children: review.value.details.map((detail, index) => jsx3("span", { className: "block break-words", children: detail }, index)) })
        ] })
      ] })
    })
  ] });
}

// plugin-source.js
import * as sdk from "@hermes/plugin-sdk";
var LOCAL_CONNECTION_ID = "local";
var REMOTE_VIEWER_UNSUPPORTED = "Remote viewers are unsupported: no viewer tunnel is available. Open Hermes on the realm machine using a local connection; forwarding only the REST endpoint over SSH is not enough.";
var validId = (value) => typeof value === "string" && value.length > 0 && value.length <= 256;
var validSession = (session) => !!session && validId(session.connectionId) && validId(session.profile) && [session.runtimeSessionId, session.storedSessionId].every((id) => id == null || validId(id)) && (validId(session.runtimeSessionId) || validId(session.storedSessionId));
var ownerBody3 = (session) => Object.fromEntries([
  ["runtime_session_id", session.runtimeSessionId],
  ["stored_session_id", session.storedSessionId]
].filter(([, value]) => validId(value)));
function realmQueryOptions(ctx, session) {
  const enabled = validSession(session);
  return {
    queryKey: ["hermes-realms", session?.connectionId, session?.profile, session?.storedSessionId, session?.runtimeSessionId],
    enabled,
    queryFn: async () => {
      if (!enabled) throw new Error("Realm session owner is unavailable");
      return ctx.rest(`/realms?${new URLSearchParams(ownerBody3(session))}`, { scope: session });
    },
    refetchInterval: 5e3,
    staleTime: 3e3,
    retry: 1,
    gcTime: 6e4
  };
}
function ownedRealms(data, session) {
  return (Array.isArray(data?.realms) ? data.realms : []).filter((realm) => /^[A-Za-z0-9_-]{1,128}$/.test(realm.id || "") && (!session.runtimeSessionId || realm.runtime_session_id === session.runtimeSessionId) && (!session.storedSessionId || realm.stored_session_id === session.storedSessionId));
}
var KIND_NAMES = { realm: "Realm", "omarchy-vm": "Omarchy VM" };
var kindName = (kind) => KIND_NAMES[kind] || "Realm";
var gib = (bytes) => Number.isFinite(bytes) && bytes > 0 ? `${(bytes / 1073741824).toFixed(1)} GB` : null;
var stateLabel = (state, t) => ({ stopped: t("stoppedState"), "recovery-required": t("recoveryState"), cleanup_failed: t("cleanupState"), deleting: t("deletingState") })[state] || (["starting", "live", "stopping", "error"].includes(state) ? state : "unknown");
function realmLabel(realm, t = (key) => setupLocales.en[key]) {
  const name = kindName(realm.kind);
  const state = stateLabel(realm.state, t);
  const control = realm.controlled ? " · user control" : "";
  if (realm.state !== "live") return `${name} · ${state}${control}`;
  if (realm.kind === "omarchy-vm") {
    const detail = [
      gib(realm.stats?.memory_bytes) && `${gib(realm.stats.memory_bytes)} RAM`,
      gib(realm.stats?.disk_bytes) && `${gib(realm.stats.disk_bytes)} disk`,
      realm.network === false && "no network"
    ].filter(Boolean).join(" · ");
    return `${name} · ${state}${detail ? ` · ${detail}` : ""}${control}`;
  }
  const count = Number.isSafeInteger(realm.window_count) && realm.window_count >= 0 ? realm.window_count : null;
  const windows = count === null ? "windows unknown" : `${count} ${count === 1 ? "window" : "windows"}`;
  return `${name} · ${windows} · ${state}${control}`;
}
async function viewerId(session, realmId) {
  const identity = new TextEncoder().encode(JSON.stringify([session.connectionId, session.profile, realmId]));
  const digest = await crypto.subtle.digest("SHA-256", identity);
  return `realm-${Array.from(new Uint8Array(digest), (value) => value.toString(16).padStart(2, "0")).join("")}`;
}
async function openRealmViewer(ctx, session, realm, target, isCurrent = () => true, isEnabled = () => true) {
  if (!validSession(session) || !ownedRealms({ realms: [realm] }, session).length) throw new Error("Realm session owner is unavailable");
  if (realm.state !== "live") throw new Error("Realm is not live");
  if (!["watch", "popout"].includes(target)) throw new Error("Unsupported viewer surface");
  if (session.connectionId !== LOCAL_CONNECTION_ID) throw new Error(REMOTE_VIEWER_UNSUPPORTED);
  const scope = Object.freeze({ ...session });
  const path = `/realms/${encodeURIComponent(realm.id)}`;
  const reply = await ctx.rest(`${path}/watch`, { method: "POST", body: ownerBody3(scope), scope });
  let url;
  try {
    url = new URL(reply.url);
  } catch {
    throw new Error("Invalid viewer URL");
  }
  if (!["http:", "https:"].includes(url.protocol) || url.username || url.password || /[\s\\]/.test(reply.url)) throw new Error("Invalid viewer URL");
  const token = new URLSearchParams(url.hash.slice(1)).get("ticket");
  if (!token || !/^[A-Za-z0-9_-]{40,128}$/.test(token)) throw new Error("Invalid viewer authorization");
  const onKeepAlive = async () => {
    if (!isEnabled()) throw new Error("Viewer plugin is disabled");
    const result = await ctx.rest(`${path}/renew`, {
      method: "POST",
      body: { ...ownerBody3(scope), viewer_token: token },
      scope
    });
    if (result?.renewed !== true) throw new Error("Viewer authorization could not be renewed");
  };
  const id = await viewerId(scope, realm.id);
  if (!isCurrent()) throw new Error("Realm owner changed before viewer opened");
  const label = `${kindName(realm.kind)} · ${scope.profile}`;
  const opened = target === "watch" ? await host.openPreview?.({ url: reply.url, label, session: scope, onKeepAlive }) : await ctx.os?.openViewer?.({ id, url: reply.url, title: label.slice(0, 120), session: scope, onKeepAlive });
  if (!opened) throw new Error("Viewer unavailable or session owner is stale");
}
var plugin_source_default = {
  id: "hermes-realms",
  defaultEnabled: false,
  name: "Realms",
  description: "Desktop viewing controls only. Enable hermes-realms under Agent plugins for each profile that should use private desktops.",
  register(ctx) {
    let enabled = true;
    ctx.onDispose?.(() => {
      enabled = false;
    });
    ctx.i18n?.register(setupLocales);
    if (sdk.PLUGIN_SETTINGS_AREA) ctx.register({
      id: "settings",
      area: sdk.PLUGIN_SETTINGS_AREA,
      data: { render: ({ scope }) => jsx4(RealmStorageSettings, { ctx, scope }) }
    });
    function StatusRow({ session }) {
      const t = useRealmText();
      const result = useQuery3(realmQueryOptions(ctx, session));
      const ownerKey = JSON.stringify(realmQueryOptions(ctx, session).queryKey);
      const currentOwner = useRef4(ownerKey);
      const deleteEpoch = useRef4(0);
      if (currentOwner.current !== ownerKey) deleteEpoch.current += 1;
      currentOwner.current = ownerKey;
      const [deleteReview, setDeleteReview] = useState4(null);
      useEffect4(() => {
        setDeleteReview(null);
      }, [ownerKey]);
      const mounted = useRef4(true);
      const pending = useRef4(/* @__PURE__ */ new Set());
      const [action, setAction] = useState4(null);
      useEffect4(() => {
        mounted.current = true;
        return () => {
          mounted.current = false;
        };
      }, []);
      async function runAction(operation, failureText) {
        if (pending.current.has(ownerKey)) return;
        pending.current.add(ownerKey);
        const current = () => mounted.current && currentOwner.current === ownerKey;
        setAction({ ownerKey, pending: true });
        try {
          await operation(current);
          if (current()) setAction(null);
        } catch {
          if (current()) setAction({ ownerKey, error: failureText });
        } finally {
          pending.current.delete(ownerKey);
        }
      }
      function open(realm, target) {
        return runAction(
          (current) => openRealmViewer(ctx, session, realm, target, current, () => enabled),
          "Unable to open viewer. Refresh the realm and try again; check viewer access for remote connections."
        );
      }
      function manage(targetAction) {
        const scope = Object.freeze({ ...session });
        return runAction(async (current) => {
          await ctx.rest("/realms/session/action", { method: "POST", body: { ...ownerBody3(scope), action: targetAction }, scope });
          if (current()) await result.refetch();
        }, t("actionError"));
      }
      function prepareDelete(realm) {
        const scope = Object.freeze({ ...session });
        const rest = ctx.rest.bind(ctx);
        const epoch = deleteEpoch.current;
        return runAction(async (current) => {
          const value = await rest(`/realms/${realm.id}/delete/prepare`, {
            method: "POST",
            body: ownerBody3(scope),
            scope
          });
          if (value?.realm_id !== realm.id || value.kind !== (realm.kind || "realm") || !["stopped", "deleting"].includes(value.state) || typeof value.consent !== "string" || !value.consent.length || !Array.isArray(value.details) || !value.details.every((detail) => typeof detail === "string")) throw new Error();
          if (current() && deleteEpoch.current === epoch) setDeleteReview({ value, scope, rest, ownerKey, epoch });
        }, t("deleteError"));
      }
      async function confirmDelete() {
        const review = deleteReview;
        if (!mounted.current || !review || review.invalid || currentOwner.current !== review.ownerKey || deleteEpoch.current !== review.epoch || pending.current.has(review.ownerKey)) throw new Error(t("deleteError"));
        pending.current.add(review.ownerKey);
        try {
          const { value, scope, rest } = review;
          const deleted = await rest(`/realms/${value.realm_id}/delete/confirm`, {
            method: "POST",
            body: { ...ownerBody3(scope), consent: value.consent },
            scope
          });
          if (deleted?.deleted !== true || deleted.realm_id !== value.realm_id) throw new Error();
          if (mounted.current && currentOwner.current === review.ownerKey && deleteEpoch.current === review.epoch) {
            const refreshed = await result.refetch();
            if (refreshed.isError) setAction({ ownerKey: review.ownerKey, deleted: value.realm_id, error: t("deleteRefreshError") });
          }
        } catch {
          if (mounted.current) setDeleteReview((current) => current === review ? { ...review, invalid: true } : current);
          throw new Error(t("deleteError"));
        } finally {
          pending.current.delete(review.ownerKey);
        }
      }
      if (!validSession(session)) return null;
      const realms = ownedRealms(result.data, session);
      if (!realms.length && result.data?.requested === false && !result.data?.setup_job) return null;
      if (result.isError && realms.length) return jsxs4("div", { role: "status", style: { fontSize: 12 }, children: [
        action?.ownerKey === ownerKey && action.deleted ? action.error : "Realm status unavailable · ",
        jsx4(Button4, { size: "micro", variant: "ghost", disabled: result.isFetching, onClick: () => void result.refetch(), children: "Retry" })
      ] });
      const mode = result.data?.mode;
      const needsPermission = result.data?.permission && result.data.permission.state !== "optional";
      const controls = needsPermission ? jsx4(RealmPermissionControls, {
        ctx,
        session,
        data: result.data,
        refresh: result.refetch
      }, ownerKey) : ["realm", "host", "ask"].includes(mode) ? jsx4(RealmSetupControls, {
        ctx,
        session,
        data: result.data,
        refresh: result.refetch
      }, ownerKey) : null;
      if (!realms.length) return controls;
      return jsxs4("div", { "data-realms-status": "", style: { display: "flex", flexDirection: "column", gap: 4 }, children: [
        controls,
        deleteReview?.ownerKey === ownerKey && deleteReview.epoch === deleteEpoch.current && jsx4(ConfirmDialog4, {
          open: true,
          destructive: true,
          title: t("deleteTitle"),
          confirmLabel: t("deleteConfirm"),
          onClose: () => setDeleteReview((current) => current === deleteReview ? null : current),
          onConfirm: confirmDelete,
          description: jsxs4("span", { className: "flex flex-col gap-3", children: [
            jsx4("span", { children: t("deleteWarning") }),
            jsx4("span", { children: `${deleteReview.scope.connectionId} · ${deleteReview.scope.profile} · ${kindName(deleteReview.value.kind)}` }),
            ...deleteReview.value.details.map((detail, index) => jsx4("span", { children: detail }, index))
          ] })
        }),
        session.connectionId !== LOCAL_CONNECTION_ID ? jsx4("span", { role: "note", children: REMOTE_VIEWER_UNSUPPORTED }) : null,
        action?.ownerKey === ownerKey && action.error && !action.deleted ? jsx4("span", { role: "alert", children: action.error }) : null,
        ...realms.map((realm) => jsxs4("div", { style: { display: "flex", alignItems: "center", flexWrap: "wrap", gap: 8, fontSize: 12 }, children: [
          jsx4("span", { children: realmLabel(realm, t) }),
          jsx4(Button4, { size: "micro", variant: "ghost", disabled: session.connectionId !== LOCAL_CONNECTION_ID || realm.state !== "live" || action?.ownerKey === ownerKey && action.pending, onClick: () => void open(realm, "watch"), children: "Watch" }),
          result.data?.requested === void 0 ? jsx4(Button4, { size: "micro", variant: "ghost", disabled: session.connectionId !== LOCAL_CONNECTION_ID || realm.state !== "live" || action?.ownerKey === ownerKey && action.pending, onClick: () => void open(realm, "popout"), children: "Pop out" }) : jsxs4(DropdownMenu, { children: [
            jsx4(DropdownMenuTrigger, { asChild: true, children: jsx4(Button4, { size: "micro", variant: "ghost", "aria-label": t("manage"), disabled: action?.ownerKey === ownerKey && action.pending, children: "⋯" }) }),
            jsxs4(DropdownMenuContent, { align: "end", children: [
              jsx4(DropdownMenuItem, { disabled: session.connectionId !== LOCAL_CONNECTION_ID || realm.state !== "live", onSelect: () => void open(realm, "popout"), children: t("popout") }),
              (realm.kind || "realm") === (result.data?.kind || "realm") && jsx4(DropdownMenuItem, { disabled: realm.state !== "live", onSelect: () => void manage("stop"), children: t("stopTesting") }),
              (realm.kind || "realm") === (result.data?.kind || "realm") && jsx4(DropdownMenuItem, { disabled: mode !== "realm", onSelect: () => void manage("off"), children: t("disableTesting") }),
              jsx4(DropdownMenuItem, { disabled: !["stopped", "deleting"].includes(realm.state), onSelect: () => void prepareDelete(realm), children: t(realm.state === "deleting" ? "retryDelete" : "deleteAction") })
            ] })
          ] }),
          realm.error ? jsx4("span", { role: "alert", children: /https?:|ticket|token/i.test(String(realm.error)) ? "Realm failed; check backend diagnostics." : String(realm.error).slice(0, 240) }) : null
        ] }, realm.id))
      ] });
    }
    function RealmBadge({ session }) {
      const t = useRealmText();
      const result = useQuery3(realmQueryOptions(ctx, session));
      if (!validSession(session)) return null;
      const owned = ownedRealms(result.data, session);
      const selected = owned.filter((realm) => (realm.kind || "realm") === result.data?.kind);
      const realms = selected.length ? selected : owned;
      if (!realms.length) return null;
      const label = `${result.isError ? "Realm status unavailable · Last known: " : ""}${realms.map((realm) => realmLabel(realm, t)).join("; ")}`;
      const vm = realms.some((realm) => realm.kind === "omarchy-vm");
      const knownCount = !vm && realms.every((realm) => Number.isSafeInteger(realm.window_count) && realm.window_count >= 0);
      const retained = realms.every((realm) => ["stopped", "recovery-required", "cleanup_failed"].includes(realm.state));
      const attention = realms.find((realm) => realm.state !== "stopped") || realms[0];
      const compact = retained ? `${kindName(attention.kind)} · ${stateLabel(attention.state, t)}` : vm ? "Omarchy VM" : knownCount ? `Realm · ${realms.reduce((sum, realm) => sum + realm.window_count, 0)}` : "Realm";
      return jsx4(Badge, { size: "xs", title: label, "aria-label": label, children: compact });
    }
    ctx.register({ id: "realm-status", area: SESSION_AREAS.statusStack, data: { render: StatusRow } });
    ctx.register({ id: "realm-tile", area: SESSION_AREAS.tileBadge, data: { render: RealmBadge } });
    ctx.register({ id: "realm-list", area: SESSION_AREAS.listBadge, data: { render: RealmBadge } });
  }
};
export {
  plugin_source_default as default,
  openRealmViewer,
  realmLabel,
  realmQueryOptions,
  viewerId
};
